### ISSUE TITLE
Quick test problem

### ISSUE THREAD

**Issue by Teaine** [openworm/c302#34]
hello
I am try to install c302 according to README.md

I have done:
git clone https://github.com/openworm/c302.git
cd c302
python setup.py install

when I try to run

owm bundle remote --user add ow 'https://raw.githubusercontent.com/openworm/owmeta-bundles/master/index.json'

I met up with the problem of 
![image](https://user-images.githubusercontent.com/22170447/114658207-0698e900-9d24-11eb-8e21-3f8d91a60e6b.png)

so I turned to run 

~/opt/anaconda3/bin/owm bundle remote --user add ow 'https://raw.githubusercontent.com/openworm/owmeta-bundles/master/index.json'

and succeed with
![image](https://user-images.githubusercontent.com/22170447/114658310-2d571f80-9d24-11eb-815e-dbb457f7e71f.png)

but afterwards, when I try to run the quick test

python c302/c302_Pharyngeal.py

I get the error of:
![image](https://user-images.githubusercontent.com/22170447/114658421-55468300-9d24-11eb-81ad-903769d7b761.png)
(The ! mark is because I added something to the dataobject.py file like this:
![image](https://user-images.githubusercontent.com/22170447/114658509-7c04b980-9d24-11eb-96d1-3e44db9560b3.png)
)

can you please give me advice to overcome this?
Thanks a lot

**Comment by mwatts15** [comment]
Hi, @Teaine , thanks for reporting this issue. Please use `pip install .` instead of `python setup.py install`. `python setup.py install` installs a pre-release version of owmeta-core, which causes the error you see. I'll update the README to recommend using pip.

Regarding this:
> I met up with the problem of
> ![image](https://user-images.githubusercontent.com/22170447/114658207-0698e900-9d24-11eb-8e21-3f8d91a60e6b.png)

Please stick to Python 3. Future versions of c302 will not necessarily run on Python 2.7 without modification and some dependencies (like owmeta) have already stopped supporting Python 2.7.

**Comment by mwatts15** [comment]
@Teaine Please, reopen this issue if the recommendations above were insufficient. Thanks again.
